package confvision

import (
	"confvision/src/auxiliar"
	"net/http"
)

var Rotas = []auxiliar.Rota{
	{
		URI:    "/carregar-menu-confvision",
		Metodo: http.MethodGet,
		Funcao: CarregarMenu,
		Aberto: false,
	},
	{
		URI:    "/cameras",
		Metodo: http.MethodGet,
		Funcao: CarregarCameras,
		Aberto: false,
	},
	{
		URI:    "/cameras/nova",
		Metodo: http.MethodGet,
		Funcao: CarregarCamerasNova,
		Aberto: false,
	},
	{
		URI:    "/cameras/editar/{id}",
		Metodo: http.MethodGet,
		Funcao: CarregarCamerasEditar,
		Aberto: false,
	},
	{
		URI:    "/eventos",
		Metodo: http.MethodGet,
		Funcao: CarregarEventos,
		Aberto: false,
	},
	{
		URI:    "/ao-vivo",
		Metodo: http.MethodGet,
		Funcao: CarregarAoVivo,
		Aberto: false,
	},
	{
		URI:    "/ao-vivo/{id}",
		Metodo: http.MethodGet,
		Funcao: CarregarAoVivoCamera,
		Aberto: false,
	},
	{
		URI:    "/gravacoes",
		Metodo: http.MethodGet,
		Funcao: CarregarGravacoes,
		Aberto: false,
	},
	{
		URI:    "/gravacoes/timeline",
		Metodo: http.MethodGet,
		Funcao: CarregarGravacoesTimeline,
		Aberto: false,
	},
	{
		URI:    "/gravacoes/dvr",
		Metodo: http.MethodGet,
		Funcao: CarregarGravacoesDvr,
		Aberto: false,
	},
	{
		URI:    "/relatorio-armado",
		Metodo: http.MethodGet,
		Funcao: CarregarRelatorioArmado,
		Aberto: false,
	},
	{
		URI:    "/relatorio-licencas",
		Metodo: http.MethodGet,
		Funcao: CarregarRelatorioLicencas,
		Aberto: false,
	},
	{
		URI:    "/relatorio-faturas",
		Metodo: http.MethodGet,
		Funcao: CarregarRelatorioFaturas,
		Aberto: false,
	},
	{
		URI:    "/grade-horario",
		Metodo: http.MethodGet,
		Funcao: CarregarGradeHorario,
		Aberto: false,
	},
	{
		URI:    "/rtmp-falhas",
		Metodo: http.MethodGet,
		Funcao: CarregarRtmpFalhas,
		Aberto: false,
	},
	{
		URI:    "/api/rtmp-falhas",
		Metodo: http.MethodGet,
		Funcao: ProxyRtmpFalhas,
		Aberto: false,
	},
	{
		URI:    "/api/rtmp-falhas/resumo",
		Metodo: http.MethodGet,
		Funcao: ProxyRtmpFalhasResumo,
		Aberto: false,
	},
	{
		URI:    "/api/rtmp-bans",
		Metodo: http.MethodGet,
		Funcao: ProxyRtmpBans,
		Aberto: false,
	},
	{
		URI:    "/api/rtmp-online",
		Metodo: http.MethodGet,
		Funcao: ProxyRtmpOnline,
		Aberto: false,
	},
	{
		URI:    "/api/rtmp-publish-health",
		Metodo: http.MethodGet,
		Funcao: ProxyRtmpPublishHealth,
		Aberto: false,
	},
	{
		URI:    "/api/rtmp-bans/unban",
		Metodo: http.MethodPost,
		Funcao: ProxyRtmpUnban,
		Aberto: false,
	},
	{
		URI:    "/api/rtmp-bans/ban",
		Metodo: http.MethodPost,
		Funcao: ProxyRtmpBan,
		Aberto: false,
	},
	{
		URI:    "/api/cameras/{id}/rtmp-publish",
		Metodo: http.MethodGet,
		Funcao: ProxyRtmpPublishURL,
		Aberto: false,
	},
	{
		URI:    "/api/cameras/{id}/bloquear",
		Metodo: http.MethodPost,
		Funcao: ProxyBloquearCamera,
		Aberto: false,
	},
	{
		URI:    "/api/clientes",
		Metodo: http.MethodPost,
		Funcao: ProxyListarClientes,
		Aberto: false,
	},
	{
		URI:    "/api/dispositivos",
		Metodo: http.MethodPost,
		Funcao: ProxyListarDispositivos,
		Aberto: false,
	},
	{
		URI:    "/api/dispositivos/por-franqueado",
		Metodo: http.MethodPost,
		Funcao: ProxyListarDispositivosFranqueado,
		Aberto: false,
	},
	{
		URI:    "/api/dispositivos/set-armado",
		Metodo: http.MethodPost,
		Funcao: ProxySetArmadoDispositivo,
		Aberto: false,
	},
	{
		URI:    "/api/dispositivos/get-armado",
		Metodo: http.MethodPost,
		Funcao: ProxyGetArmadoDispositivo,
		Aberto: false,
	},
	{
		URI:    "/api/dispositivo-dados",
		Metodo: http.MethodPost,
		Funcao: ProxyDadosDispositivo,
		Aberto: false,
	},
	{
		URI:    "/api/setores",
		Metodo: http.MethodPost,
		Funcao: ProxyListarSetores,
		Aberto: false,
	},
	{
		URI:    "/api/cameras",
		Metodo: http.MethodGet,
		Funcao: ProxyListarCameras,
		Aberto: false,
	},
	{
		URI:    "/api/licencas",
		Metodo: http.MethodGet,
		Funcao: ProxyListarLicencas,
		Aberto: false,
	},
	{
		URI:    "/api/licencas",
		Metodo: http.MethodPost,
		Funcao: ProxyCriarLicenca,
		Aberto: false,
	},
	{
		URI:    "/api/cameras",
		Metodo: http.MethodPost,
		Funcao: ProxyCriarCamera,
		Aberto: false,
	},
	{
		URI:    "/api/cameras/{id}",
		Metodo: http.MethodGet,
		Funcao: ProxyGetCamera,
		Aberto: false,
	},
	{
		URI:    "/api/cameras/{id}",
		Metodo: http.MethodPut,
		Funcao: ProxyAtualizarCamera,
		Aberto: false,
	},
	{
		URI:    "/api/cameras/{id}/snapshot",
		Metodo: http.MethodPost,
		Funcao: TirarSnapshotCamera,
		Aberto: false,
	},
	{
		URI:    "/api/cameras/{id}/snapshot",
		Metodo: http.MethodDelete,
		Funcao: RemoverSnapshotCamera,
		Aberto: false,
	},
	{
		URI:    "/api/cameras/{id}/areas",
		Metodo: http.MethodGet,
		Funcao: ProxyListarCameraAreas,
		Aberto: false,
	},
	{
		URI:    "/api/cameras/{id}/areas",
		Metodo: http.MethodPost,
		Funcao: ProxyCriarCameraArea,
		Aberto: false,
	},
	{
		URI:    "/api/camera-areas/{id}",
		Metodo: http.MethodPut,
		Funcao: ProxyAtualizarCameraArea,
		Aberto: false,
	},
	{
		URI:    "/api/camera-areas/{id}",
		Metodo: http.MethodDelete,
		Funcao: ProxyExcluirCameraArea,
		Aberto: false,
	},
	{
		URI:    "/api/eventos",
		Metodo: http.MethodGet,
		Funcao: ProxyListarEventos,
		Aberto: false,
	},
	{
		URI:    "/api/eventos/{id}/clips",
		Metodo: http.MethodGet,
		Funcao: ProxyGetEventoClips,
		Aberto: false,
	},
	{
		URI:    "/api/gravacao-storage",
		Metodo: http.MethodGet,
		Funcao: ProxyListarGravacaoStorage,
		Aberto: false,
	},
	{
		URI:    "/api/gravacao-storage",
		Metodo: http.MethodPost,
		Funcao: ProxyCriarGravacaoStorage,
		Aberto: false,
	},
	{
		URI:    "/api/gravacao-storage/{id}",
		Metodo: http.MethodPut,
		Funcao: ProxyAtualizarGravacaoStorage,
		Aberto: false,
	},
	{
		URI:    "/api/cameras/{id}/gravacao/ativar",
		Metodo: http.MethodPost,
		Funcao: ProxyAtivarGravacaoCamera,
		Aberto: false,
	},
	{
		URI:    "/api/cameras/{id}/gravacao/desativar",
		Metodo: http.MethodPost,
		Funcao: ProxyDesativarGravacaoCamera,
		Aberto: false,
	},
	{
		URI:    "/api/cameras/{id}/licenca/liberar",
		Metodo: http.MethodPost,
		Funcao: ProxyLiberarLicencaCamera,
		Aberto: false,
	},
	{
		URI:    "/api/cameras/{id}/gravacao/flush",
		Metodo: http.MethodPost,
		Funcao: ProxyFlushGravacaoCamera,
		Aberto: false,
	},
	{
		URI:    "/api/cameras/{id}/analitico/pausar",
		Metodo: http.MethodPost,
		Funcao: ProxyPausarAnaliticoCamera,
		Aberto: false,
	},
	{
		URI:    "/api/gravacao-segmentos",
		Metodo: http.MethodGet,
		Funcao: ProxyListarGravacaoSegmentos,
		Aberto: false,
	},
	{
		URI:    "/api/grade-cliente/{id_cliente}",
		Metodo: http.MethodGet,
		Funcao: ProxyGetGradeCliente,
		Aberto: false,
	},
	{
		URI:    "/api/grade-cliente/{id_cliente}",
		Metodo: http.MethodPut,
		Funcao: ProxyPutGradeCliente,
		Aberto: false,
	},
	{
		URI:    "/api/grades",
		Metodo: http.MethodGet,
		Funcao: ProxyGetGradeList,
		Aberto: false,
	},
	{
		URI:    "/api/grade-escopo-ativa",
		Metodo: http.MethodPatch,
		Funcao: ProxyPatchGradeEscopoAtiva,
		Aberto: false,
	},
	{
		URI:    "/api/gravacao-segmento/video",
		Metodo: http.MethodGet,
		Funcao: ProxyGravacaoSegmentoVideo,
		Aberto: false,
	},
}
